### ISSUE TITLE
Stepping in the poison water causes a server packet error which disconnects the client.

### ISSUE THREAD

**Issue by Magicrafter13** [Frozeh/infinity-cave#4]
When stepping into the poison water, this happens. It seems to be an issue somewhere with the advancement. Which means the issue continues to happen every time the player steps in.
```
[20:28:31] [Server thread/WARN]: Failed to handle packet for /(client)
net.minecraft.class_148: Ticking player
        at net.minecraft.class_3222.method_14226(class_3222.java:583) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_18784(class_3244.java:257) ~[server-intermediary.jar:?]
        at net.minecraft.class_2535.method_10754(class_2535.java:379) ~[server-intermediary.jar:?]
        at net.minecraft.class_3242.method_14357(class_3242.java:176) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:959) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:283) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:845) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:683) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:1623) ~[?:?]
Caused by: java.lang.NoSuchMethodError: 'net.minecraft.class_161 net.minecraft.class_2989.method_12896(net.minecraft.class_2960)'
        at net.mcreator.extraadvancements.procedures.PoisonadvancementProcedure.execute(PoisonadvancementProcedure.java:44) ~[extra-advancements-v0.1.0-fabric.jar:?]
        at net.mcreator.extraadvancements.procedures.PoisonadvancementProcedure.lambda$new$0(PoisonadvancementProcedure.java:30) ~[extra-advancements-v0.1.0-fabric.jar:?]
        at net.fabricmc.fabric.api.entity.event.v1.ServerLivingEntityEvents.lambda$static$0(ServerLivingEntityEvents.java:37) ~[fabric-entity-events-v1-1.6.0+44c0f8c64f-7ce1a7d23e4e0c8.jar:?]
        at net.minecraft.class_1309.handler$zmc000$fabric-entity-events-v1$beforeDamage(class_1309.java:6264) ~[server-intermediary.jar:?]
        at net.minecraft.class_1309.method_5643(class_1309.java:1147) ~[server-intermediary.jar:?]
        at net.minecraft.class_1657.method_5643(class_1657.java:938) ~[server-intermediary.jar:?]
        at net.minecraft.class_3222.method_5643(class_3222.java:738) ~[server-intermediary.jar:?]
        at net.minecraft.class_8635.method_5572(class_8635.java:14) ~[server-intermediary.jar:?]
        at net.minecraft.class_1293.method_5585(class_1293.java:191) ~[server-intermediary.jar:?]
        at net.minecraft.class_1309.method_6050(class_1309.java:815) ~[server-intermediary.jar:?]
        at net.minecraft.class_1309.method_5670(class_1309.java:458) ~[server-intermediary.jar:?]
        at net.minecraft.class_1297.method_5773(class_1297.java:477) ~[server-intermediary.jar:?]
        at net.minecraft.class_1309.method_5773(class_1309.java:2407) ~[server-intermediary.jar:?]
        at net.minecraft.class_1657.method_5773(class_1657.java:284) ~[server-intermediary.jar:?]
        at net.minecraft.class_3222.method_14226(class_3222.java:519) ~[server-intermediary.jar:?]
        ... 9 more
```

**Comment by Frozeh** [comment]
Seems to be some mcreator mod that is causing the crash. It looks like an incompatibility. Could you list the Minecraft version and mods you are using?

**Comment by Magicrafter13** [comment]
Nevermind, I believe this was actually caused by an "Extra Advancements" mod, seems anything that attempted to afflict a player with poison caused this.
